# Use an official Node runtime as a parent image
FROM node:18-alpine as BUILD_IMAGE

# Set the working directory to /app
WORKDIR /app/react-app

# Copy package.json and package-lock.json to the working directory
COPY package.json .

# Install any needed packages specified in package.json
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .


# Run app.js when the container launches
CMD npm run build




FROM node:18-alpine as PRODUCTION_IMAGE
WORKDIR /app/react-app

COPY --from=BUILD_IMAGE /app/react-app/dist/ /app/react-app/dist/
EXPOSE 8080
COPY package.json .
COPY vite.config.js .
RUN npm install
EXPOSE 8080
CMD [ "npm","run","preview" ]